"""rename message

Revision ID: e92c1bbe4059
Revises: 7ef3754ca9fb
Create Date: 2024-03-14 15:27:38.387396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92c1bbe4059'
down_revision: Union[str, None] = '7ef3754ca9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_reciepient_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    op.drop_column('message', 'reciepient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reciepient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_reciepient_id_fkey', 'message', 'user', ['reciepient_id'], ['id'])
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###
