"""create_message2

Revision ID: 47cdb568782c
Revises: fe897ace8bb3
Create Date: 2024-03-12 13:52:04.192102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47cdb568782c'
down_revision: Union[str, None] = 'fe897ace8bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('reciepien_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['reciepien_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'is_active')
    op.drop_column('message', 'registered_at')
    op.drop_column('message', 'is_superuser')
    op.drop_column('message', 'name')
    op.drop_column('message', 'surname')
    op.drop_column('message', 'is_verified')
    op.drop_column('message', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'reciepien_id')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
