"""rename_message

Revision ID: 7ef3754ca9fb
Revises: 
Create Date: 2024-03-14 11:21:41.984576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef3754ca9fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reciepient_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_reciepien_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['reciepient_id'], ['id'])
    op.drop_column('message', 'reciepien_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reciepien_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_reciepien_id_fkey', 'message', 'user', ['reciepien_id'], ['id'])
    op.drop_column('message', 'reciepient_id')
    # ### end Alembic commands ###
