"""add message timestamp

Revision ID: 5a037eb76cce
Revises: 7cb8ccff2ede
Create Date: 2024-03-13 14:46:57.994903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a037eb76cce'
down_revision: Union[str, None] = '7cb8ccff2ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###
